### ISSUE TITLE
does not hide when viewed at speeds greater than 2x

### ISSUE THREAD

**Issue by WitekS** [Mandrenkov/FreshView#1]
I usually watch at an increased speed and then it doesn't work, i.e. it doesn't hide the movies I watched.

**Comment by Mandrenkov** [comment]
Do you mind providing specific instructions to reproduce this bug?

Here's what I tried:
1. Watched a [YouTube video](https://youtu.be/Sb7D_BlQxfM) at 2x playback speed.
1. Navigated to the YouTube homepage.
1. Searched for "Thermal View of a Geyser" (i.e., the video I just watched).

When I do this, the extension correctly hides the video.

It's possible that YouTube, for whatever reason, isn't properly tracking your view progress which is why the extension fails to hide your videos.  In general, FreshView looks for the red progress bar along the bottom of a video thumbnail to judge the view progress of a video.

**Comment by WitekS** [comment]
I checked everything according to the instructions and everything works properly maybe it is a problem with the subscription page extension that I use to hide Better Subscriptions for YouTube ™ and which works for me has some additional time setting Refresh frequency for cleaning the channel (milliseconds) and you can see that after a while viewed videos from the subscription disappear ...
Earlier, I watched a few movies at normal speed and these movies disappeared after watching the subscription, so I thought it was a problem with the speed of watching but it is probably something else ...
Probably the problem is that not all watched videos are not marked as watched. I watched several movies at x2.7 speed and some are marked as watched after viewing and others are not and I don't know where to look for the reason ...

**Comment by Mandrenkov** [comment]
Thanks for the update!  It's possible that [Better Subscription for YouTube™](https://chrome.google.com/webstore/detail/better-subscriptions-for/fkchdogohkjpnhfkganifkbbjcjofbjf) changes the DOM in some way that conflicts with FreshView.  I'll check out the extension when I have some time and see if I can reproduce the issue.

**Comment by WitekS** [comment]
Although FreshView for YouTube ™ does not hide all the videos I watched on the subscription page, I will stay with it because I like it better. I did some more tests and here is e.g. the movie https://www.youtube.com/watch?v=vu7eZyKX5z0 which is hidden after viewing on the home page but does not disappear on the subscription page.
As for me, it would be useful to show some info that the movie is already classified as viewed and hidden, e.g. some popup or something else, such as the extension https://chrome.google.com/webstore/detail/youtube-auto- like / loodalcnddclgnfekfomcoiipiohcdim

**Comment by Mandrenkov** [comment]
I played around with Better Subscriptions and found that FreshView still works as expected in the Subscriptions tab.  I don't know why Better Subscriptions doesn't properly hide all the videos it tags with the "Watched" watermark (even after uninstalling FreshView), but that's a question for the Better Subscriptions team.  I'll emphasize again that FreshView tracks view progress by measuring the red progress bar along the bottom of a video thumbnail; Better Subscriptions does something else.

Regarding your other point, I don't think that adding a tooltip or other subtle indicator for watched videos (with respect to the current View Threshold position) is particularly helpful because you can always just look at the red progress bar on the thumbnail and judge for yourself.  I have considered adding a toggle to "fade" videos instead of hiding them outright, but it will be some time before I get around to implementing it.

**Comment by WitekS** [comment]
OK, I understand that everything works fine for you, unfortunately not from what I checked, that the problem is with hiding the videos viewed on the YouTube subscription page. Initially, I thought it had to do with playback speed but this is not the reason. Can you add some optional debugging mode so that you can check why these videos aren't hiding with me? Maybe some other extension or e.g. removing ads has some influence on it ... Probably there are some conditions for hiding the movie you watched, which in debug mode you could check if any logs from this mode are met could explain something more ...

**Comment by WitekS** [comment]
I found a solution and it works now. There was a problem saving your watch history.
