### ISSUE TITLE
Documentation: Compare with other software

### ISSUE THREAD

**Issue by BradKML** [Mandrenkov/FreshView#9]
Here are some software that should be made aware of:
- https://github.com/OsaSoft/youtube-better-subscriptions
- https://chrome.google.com/webstore/detail/freshview-for-youtube/eckknmnfoohbeklmjlidmfdlakndcfkm?hl=en
- https://chrome.google.com/webstore/detail/watchmarker-for-youtube/pfkkfbfdhomeagojoahjmkojeeepcolc?hl=en
- https://chrome.google.com/webstore/detail/youtube-subfilter-extensi/pgfmiggljohpblgjgbglmloiffafgadg?hl=en

Question:
1. How are features differ, other than blocklists, finding watched videos, and knowing when to block?
2. Can these software be reimplemented in GreaseMonkey?

**Comment by Mandrenkov** [comment]
Hello,

Thanks for taking the time to leave an issue! 👍

Can you clarify what problem this documentation is aiming to solve? It is usually quite rare to see a first-party product survey included in the documentation of a product since it is likely to be biased and takes nontrivial effort to keep up-to-date.

Thanks!
